title: Sancharika Debnath
description: Hi, I'm a dynamic Data Scientist with a passion for leveraging cutting-edge technology to craft innovative solutions and drive meaningful change through data-driven insights.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
